parameters:
#    kj_payment_stripe.example.class: KJ\Payment\StripeBundle\Example

services:
#    kj_payment_stripe.example:
#        class: %kj_payment_stripe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
